name: Publish

on:
  push:
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: zulu
          cache: gradle

      - run: git submodule update --init --recursive

      - name: Decrypt CloudRepo credentials
        run: ./config/scripts/decrypt.sh "$CLOUDREPO_CREDENTIALS_KEY" ./.github/keys/cloudrepo.properties.gpg ./cloudrepo.properties
        env:
          CLOUDREPO_CREDENTIALS_KEY: ${{ secrets.CLOUDREPO_CREDENTIALS_KEY }}

      - name: Decrypt GCAR credentials
        run: ./config/scripts/decrypt.sh "$MAVEN_PUBLISHER_KEY" ./.github/keys/maven-publisher.json.gpg ./maven-publisher.json
        env:
          MAVEN_PUBLISHER_KEY: ${{ secrets.MAVEN_PUBLISHER_KEY }}

      - name: Publish artifacts to Maven
        run: ./gradlew assemble publish --stacktrace
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ./maven-publisher.json
